# Setup
title: 'Ajay Melekamburath'
tagline: ''
description: 'A blog based on <a href="https://jekyllrb.com" target="_blank">Jekyll</a>.'
url: https://ajay-mk.github.io
baseurl: 'ajay-mk.github.io'
permalink: pretty
# About/contact
author: Ajay
name: 'Ajay M K'
url: https://twitter.com/ajaymk_

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y

